### ISSUE TITLE
Remove space on the right for the related tabs if there is no related tabs

### ISSUE THREAD

**Issue by dafortin** [ciena-frost/ember-frost-object-details#27]

**Comment by srowhani** [comment]
![screen shot 2017-01-31 at 1 26 36 pm](https://cloud.githubusercontent.com/assets/7063255/22484266/9a88b330-e7ce-11e6-9eec-44857a9d45fa.png)
![screen shot 2017-01-31 at 1 25 48 pm](https://cloud.githubusercontent.com/assets/7063255/22484265/9a88bdee-e7ce-11e6-849c-2c46afa079d8.png)
