### ISSUE TITLE
Switching between tabs cause losing context information

### ISSUE THREAD

**Issue by dafortin** [ciena-frost/ember-frost-object-details#37]
**Tab Content**
Default tab: We created a tab with some `svgs` that have `filter/fill` based on `defs`. 
Second tab: any content

**Steps to reproduce**
1. Wait for the first tab to load (the one that contains svgs)
2. Select another tab
3. Come back to the initial tab
4. Go hover an svg element with a `filter/fill` defined in `defs`

You will notice that the `filter/fill` will not be applied. It looks like we are losing the context (`url(....)`) once we switch from one tab to the other.

**Comment by sglanzer** [comment]
Symptom of #42
